name: Multi_EVENTS_TRIGGER

# on: [pull_request_target, issues, feature/**]
on:
  push:
    branches:
      - 'feature/**'
      - 'main'
  pull_request:
    branches: [ $default-branch ]

jobs:
  Multi_EVENT_EXAMPLE:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Basic Information
        run: |
          echo "Ref: $GITHUB_REF"
          echo "Job Id: $GITHUB_JOB"
          echo "Action: $GITHUB_ACTION"
          echo "Actor: $GITHUB_ACTOR"